In [ ]:
import numpy as np
x = np.array([1, 2, 3])
y = (x == 2)
y

array([False,  True, False])

In [ ]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = x1.copy()
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.vstack([x1, x2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack([x1, x2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])