In [1]:
import pandas as pd

In [2]:
import gdown
url = 'https://drive.google.com/uc?export=download&id=1EYGudsvgwHA04DvHnR5C3NrkcumycH-M'
output= 'SMSSpamCollection.txt'
gdown.download(url, output, quiet=False)

Downloading...
From: https://drive.google.com/uc?export=download&id=1EYGudsvgwHA04DvHnR5C3NrkcumycH-M
To: /content/SMSSpamCollection.txt
100%|██████████| 478k/478k [00:00<00:00, 63.6MB/s]


'SMSSpamCollection.txt'

In [3]:
uri = 'SMSSpamCollection.txt'
df = pd.read_table(uri, sep='\t', header=None, names=['label', 'sms_message'])

# printing out first 5 rows
df.head()

label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# map the 'ham' value to 0 and the 'spam' value to 1.
df['label'] = df.label.map({'ham':0,'spam':1})
# Number of rows and column
df.shape

(5572, 2)

In [5]:
df

label                                        sms_message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0               Will ü b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
# Use from sklearn.model_selection import train_test_split to avoid seeing deprecation warning.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['sms_message'], 
                                                    df['label'], 
                                                    random_state=1)

print('Number of rows in the total set: {}'.format(df.shape[0]))
print('Number of rows in the training set: {}'.format(X_train.shape[0]))
print('Number of rows in the test set: {}'.format(X_test.shape[0]))



Number of rows in the total set: 5572
Number of rows in the training set: 4179
Number of rows in the test set: 1393


In [7]:
y_test

1078    0
4028    0
958     0
4642    0
4674    0
       ..
3207    0
4655    0
1140    0
1793    1
1710    0
Name: label, Length: 1393, dtype: int64

In [8]:
# Data preprocessing with CountVectorizer()
# Import the CountVectorizer method
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
# Instantiate the CountVectorizer method
count_vector = CountVectorizer()
X_train

710     4mths half price Orange line rental & latest c...
3740                           Did you stitch his trouser
2711    Hope you enjoyed your new content. text stop t...
3155    Not heard from U4 a while. Call 4 rude chat pr...
3748    Ü neva tell me how i noe... I'm not at home in...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: sms_message, Length: 4179, dtype: object

In [10]:
X_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [11]:
# Fit the training data
training_data = count_vector.fit_transform(X_train)
print(training_data[1000])
print(X_train[1000])
# stopped here

  (0, 6571)	1
  (0, 2320)	1
  (0, 3244)	1
  (0, 3221)	1
  (0, 3193)	1
  (0, 6096)	1
Aight will do, thanks again for comin out


In [33]:
type(training_data[1000])

scipy.sparse.csr.csr_matrix

In [34]:
training_data.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
training_data[1000].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [36]:
len(training_data[1000].toarray())

1

In [37]:
len(training_data[1000].toarray()[0])

7456

In [39]:
oneDocArray = training_data[1000].toarray()[0]
min(oneDocArray), max(oneDocArray)

(0, 1)

In [ ]:
# stopped here
# for, computing the max frequency over all

In [12]:

# Transform testing data
testing_data = count_vector.transform(X_test)


In [13]:
str(training_data[0])

'  (0, 509)\t1\n  (0, 3181)\t1\n  (0, 5193)\t1\n  (0, 4781)\t1\n  (0, 3971)\t1\n  (0, 5479)\t1\n  (0, 3880)\t1\n  (0, 1572)\t1\n  (0, 4987)\t1\n  (0, 2864)\t2\n  (0, 3170)\t1\n  (0, 7424)\t1\n  (0, 4983)\t1\n  (0, 264)\t1\n  (0, 1552)\t1\n  (0, 4375)\t1\n  (0, 4743)\t1\n  (0, 50)\t1\n  (0, 6656)\t1\n  (0, 6892)\t1\n  (0, 4662)\t1\n  (0, 4779)\t1\n  (0, 2022)\t1'

In [14]:
X_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [15]:
y_train[0]

0

In [16]:
# Implementing Naive Bayes using scikit-learn
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()
naive_bayes.fit(training_data, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
# Prediciting the messages as spam or ham -- testing data
predictions = naive_bayes.predict(testing_data)

In [18]:
# print(testing_data)

In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print('Accuracy score: {}'.format(accuracy_score(y_test, predictions)))
print('Precision score: {}'.format(precision_score(y_test, predictions)))
print('Recall score: {}'.format(recall_score(y_test, predictions)))
print('F1 score: {}'.format(f1_score(y_test, predictions)))

Accuracy score: 0.9885139985642498
Precision score: 0.9720670391061452
Recall score: 0.9405405405405406
F1 score: 0.9560439560439562


In [20]:
predictions = naive_bayes.predict(training_data)
print('Accuracy score: {}'.format(accuracy_score(y_train, predictions)))
print('Precision score: {}'.format(precision_score(y_train, predictions)))
print('Recall score: {}'.format(recall_score(y_train, predictions)))
print('F1 score: {}'.format(f1_score(y_train, predictions)))

Accuracy score: 0.9923426657094999
Precision score: 0.974910394265233
Recall score: 0.9679715302491103
F1 score: 0.9714285714285714


In [21]:
# testing_data = count_vector.transform(["Best price"])
# predictions = naive_bayes.predict(testing_data)
# print('Accuracy score: {}'.format(accuracy_score(y_test, predictions)))

sample = ["Best price", "Free ticket for you", "india best 800", "Black lives matter", "Free entry in 2 a for you "]
testing_data = count_vector.transform(sample)
predictions = naive_bayes.predict(testing_data)
predictions

array([0, 0, 1, 0, 1])

**Example** Count vectorizer

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

# list of text documents
text = ["John is a good boy. John watches basketball"]

vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(text)

print(vectorizer.vocabulary_)

# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

{'john': 4, 'is': 3, 'good': 2, 'boy': 1, 'watches': 5, 'basketball': 0}
(1, 6)
[[1 1 1 1 2 1]]


In [23]:
type(vector)

scipy.sparse.csr.csr_matrix

In [24]:
print(vector)

  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	2
  (0, 5)	1


In [25]:
import numpy as np

# Initializing
vectorizer = CountVectorizer()
# Composing the core
corpus = [
  'word1 word2 word3',
  'word2 word3',
  'word1 word2 word1',
  'word4'
]
# подсчитываем
X = vectorizer.fit_transform(corpus)
 
# Thus, the following structure will be computed:
#        | word1 | word2 | word3 | word4
# text1 |   1    |    1   |   1    |   0
# text2 |   0    |    1   |   1    |   0
# text3 |   2    |    1   |   0    |   0
# text4 |   0    |    0   |   0    |   1

# Stopped here
 


In [26]:
# чтобы получить сгенерированный словарь, из приведенной структуры CountVectorizer, стоит отметить что порядок совпадает с матрицей
vectorizer.get_feature_names()  # ['слово1', 'слово2', 'слово3', 'слово4']

['word1', 'word2', 'word3', 'word4']

In [27]:
# чтобы узнать индекс токена в словаре
vectorizer.vocabulary_.get('слово3') # вернет 2

In [28]:
# показать матрицу
X.toarray()

array([[1, 1, 1, 0],
       [0, 1, 1, 0],
       [2, 1, 0, 0],
       [0, 0, 0, 1]])

In [29]:
# теперь можно быстро подсчитать вектор для нового документа
vectorizer.transform(["слово1 слово4 слово4"])  # результат [[1 0 0 2]]

<1x4 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [30]:
# чтобы узнать количественное вхождение каждого слова:
matrix_freq = np.asarray(X.sum(axis=0)).ravel()
matrix_freq

array([3, 3, 2, 1], dtype=int64)

In [31]:
final_matrix = np.array([np.array(vectorizer.get_feature_names()), matrix_freq])
final_matrix

array([['word1', 'word2', 'word3', 'word4'],
       ['3', '3', '2', '1']], dtype='<U21')